FROM mautic/mautic:5.1-apache

ARG MYSQL_DATABASE
ARG MYSQL_HOST
ARG MYSQL_PASSWORD
ARG MYSQL_PORT
ARG MYSQL_ROOT_PASSWORD
ARG MYSQL_USER

ENV MYSQL_DATABASE
ENV MYSQL_HOST
ENV MYSQL_PASSWORD
ENV MYSQL_PORT
ENV MYSQL_ROOT_PASSWORD
ENV MYSQL_USER

ENV PHP_INI_DATE_TIMEZONE='UTC'
